language: python
python:
  - 3.7
sudo: false
addons:
  apt_packages:
    - pandoc
env:
  matrix:
    - GROUP=python
matrix:
  include:
    - python: 3.7
      env: GROUP=python
    - python: 3.7
      env: GROUP=docs
cache:
  pip: true
  directories:
    - node_modules
    - $HOME/.npm
before_install:
  - pip install -U pip setuptools
  - nvm install 8
install:
  - |
    if [[ $GROUP == python ]]; then
      pip install --upgrade -e ".[test]" -v
    elif [[ $GROUP == docs ]]; then
      pip install --upgrade -e ".[test, docs]" -v
    fi
script:
  - |
    if [[ $GROUP == python ]]; then
      EXIT_STATUS=0
      pushd $(mktemp -d)
      py.test -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov=algorithmx --pyargs algorithmx || EXIT_STATUS=$?
      popd
      (exit $EXIT_STATUS)
    elif [[ $GROUP == docs ]]; then
      EXIT_STATUS=0
      cd docs
      make html || EXIT_STATUS=$?
      make linkcheck || EXIT_STATUS=$?
      cd ..
      python -m pytest_check_links --links-ext=.md -o testpaths=. -o addopts= || EXIT_STATUS=$?
      (exit $EXIT_STATUS)
    fi
after_success:
  - codecov
