name: algorithmx_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - babel=2.8.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - commonmark=0.9.1
  - cryptography=2.8
  - decorator=4.4.1
  - defusedxml=0.6.0
  - docutils=0.15.2
  - entrypoints=0.3
  - future=0.18.2
  - idna=2.8
  - imagesize=1.2.0
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.2
  - jinja2=2.10.3
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - jupyter_sphinx=0.2.3
  - libcxx=9.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libsodium=1.0.16
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - nbsphinx=0.5.0
  - ncurses=6.1
  - networkx=2.4
  - notebook=6.0.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - packaging=20.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.0
  - readline=7.0
  - recommonmark=0.6.0
  - requests=2.22.0
  - send2trash=1.5.0
  - setuptools=44.0.0
  - six=1.13.0
  - snowballstemmer=2.0.0
  - sphinx=2.3.1
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.7
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - html5lib==1.0.1
    - pluggy==0.13.1
    - py==1.8.1
    - pytest==5.3.4
    - pytest-check-links==0.3.0
